name = "NLSA"
uuid = "e2e491fc-7d8f-4591-840c-7964746acd08"
authors = ["clairevalva <clairev@nyu.edu> and contributors"]
version = "0.1.0"

[deps]
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
